
function sendEmails() { // Display a confirmation message when 'Send emails' button is clicked
  let emailMessage = document.getElementById('message');
  emailMessage.innerHTML = 'Email(s) sent!';
}

function requestBill() { // AJAX request for awardee bill XML file on server (generated by Registrar Office)
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      showBill(this);
    }
  };
  xhttp.open("GET", "awardee_bill.xml", true);
  xhttp.send();
}

function showBill(xml) {
  var xmlDoc = xml.responseXML;
  var bill = xmlDoc.getElementsByTagName("bill")[0].childNodes[0].nodeValue;
  document.getElementById("bill").value = '$'+bill.trim();
}

window.addEventListener('load', function() {
  // Loop through dropdown buttons to toggle between hiding and showing dropdown content
  var dropdown = document.getElementsByClassName("dropdown");

  for (let i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function() {
      this.classList.toggle("open");
      let dropdownLinks = this.nextElementSibling;
      if (dropdownLinks.style.display === "block") {
        dropdownLinks.style.display = "none";
      }
      else {
        dropdownLinks.style.display = "block";
      }
    });
  }

  if (document.getElementById("bill")) { // Reset bill input box each time
    document.getElementById("bill").value = '';
  }

  if (document.getElementById("json_quote")) { // API call to retrieve random quotes in JSON and display on home page
    fetch("https://type.fit/api/quotes")
      .then(function(response) {
        return response.json();
      })
      .then(function(data) {
        console.log(data);
        randomQuote = data[Math.floor(Math.random() * 1642)]['text'];
        randomAuthor = data[Math.floor(Math.random() * 1642)]['author'];
        console.log(randomQuote);
        console.log(randomAuthor);
        document.getElementById("json_quote").innerHTML = randomQuote;
        if (randomAuthor == null) {
          document.getElementById("json_author").innerHTML = "~ Unknown";
        }
        else {
          document.getElementById("json_author").innerHTML = "~ " + randomAuthor;
        }
      });
  }
});
